import type { NewSource } from "@/lib/db/schema";

/**
 * Seed sources — Tier 1-4 from the MVP plan §6.
 * IDs are human-readable slugs (TEXT primary key by design).
 * Weights inform article scoring (see §7.6).
 */
export const seedSources: NewSource[] = [
  // ─── Tier 1: official high-signal sources ─────────────────
  {
    id: "openai-blog",
    name: "OpenAI Blog",
    url: "https://openai.com/blog/rss.xml",
    type: "rss",
    category: "models",
    tier: 1,
    priority: "high",
    weight: 30,
    refreshIntervalMinutes: 60,
    description: "Official OpenAI announcements, research, and product updates.",
    tags: ["official", "model-provider"],
  },
  {
    id: "anthropic-news",
    name: "Anthropic News",
    // No public RSS; we pull anthropic.com/sitemap.xml and filter /news/ entries by lastmod.
    url: "https://www.anthropic.com/sitemap.xml",
    type: "sitemap",
    category: "models",
    tier: 1,
    priority: "high",
    weight: 30,
    refreshIntervalMinutes: 60,
    description: "Official Anthropic announcements via sitemap (no RSS). Title is slug-derived until enrichment fetches og:title.",
    tags: ["official", "model-provider", "sitemap:prefix=/news/", "sitemap:limit=50"],
  },
  {
    id: "anthropic-engineering",
    name: "Anthropic Engineering",
    url: "https://www.anthropic.com/sitemap.xml",
    type: "sitemap",
    category: "infra",
    tier: 1,
    priority: "high",
    weight: 28,
    refreshIntervalMinutes: 180,
    description: "Anthropic engineering posts (Claude Code, postmortems, agent how-tos) via sitemap.",
    tags: ["official", "engineering", "sitemap:prefix=/engineering/", "sitemap:limit=50"],
  },
  {
    id: "google-ai-blog",
    name: "Google AI Blog",
    url: "https://blog.google/technology/ai/rss/",
    type: "rss",
    category: "models",
    tier: 1,
    priority: "high",
    weight: 25,
    refreshIntervalMinutes: 60,
    description: "Google's AI research and product blog.",
    tags: ["official", "model-provider"],
  },
  {
    id: "huggingface-blog",
    name: "Hugging Face Blog",
    url: "https://huggingface.co/blog/feed.xml",
    type: "rss",
    category: "infra",
    tier: 1,
    priority: "high",
    weight: 20,
    refreshIntervalMinutes: 90,
    description: "Open-source models, datasets, and ML engineering posts.",
    tags: ["official", "open-source"],
  },

  // ─── Tier 2: industry analysis & media ────────────────────
  {
    id: "techcrunch-ai",
    name: "TechCrunch AI",
    url: "https://techcrunch.com/category/artificial-intelligence/feed/",
    type: "rss",
    category: "media",
    tier: 2,
    priority: "medium",
    weight: 15,
    refreshIntervalMinutes: 120,
    description: "AI startup and industry coverage.",
    tags: ["media"],
  },
  {
    id: "the-verge-ai",
    name: "The Verge AI",
    url: "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml",
    type: "rss",
    category: "media",
    tier: 2,
    priority: "medium",
    weight: 15,
    refreshIntervalMinutes: 120,
    description: "Consumer-facing AI product and policy coverage.",
    tags: ["media"],
  },
  {
    id: "mit-tech-review-ai",
    name: "MIT Technology Review — AI",
    url: "https://www.technologyreview.com/topic/artificial-intelligence/feed",
    type: "rss",
    category: "media",
    tier: 2,
    priority: "medium",
    weight: 15,
    refreshIntervalMinutes: 180,
    description: "In-depth AI analysis and longform reporting.",
    tags: ["media", "analysis"],
  },

  // ─── Tier 3: community & trend signals ────────────────────
  {
    id: "reddit-claudecode",
    name: "Reddit r/ClaudeCode",
    url: "https://www.reddit.com/r/ClaudeCode/.rss",
    type: "rss",
    category: "community",
    tier: 3,
    priority: "medium",
    weight: 12,
    refreshIntervalMinutes: 90,
    description: "Real-world Claude Code usage, gripes, tips.",
    tags: ["community", "coding-agent"],
  },
  {
    id: "steve-yegge-blog",
    name: "Steve Yegge — Stevey's Blog Rants",
    url: "https://steve-yegge.blogspot.com/feeds/posts/default",
    type: "rss",
    category: "community",
    tier: 3,
    priority: "low",
    weight: 10,
    refreshIntervalMinutes: 360,
    description: "Long-form essays on coding agents and dev tools.",
    tags: ["community", "essay"],
  },

  // ─── Tier 4: research (arXiv) ─────────────────────────────
  // We use the official Atom API (export.arxiv.org/api/query), not the
  // legacy /rss/ endpoint which rss-parser cannot decode reliably.
  // Rate limited internally to 1 req per 3s per arXiv guidance.
  {
    id: "arxiv-cs-ai",
    name: "arXiv cs.AI",
    url: "https://export.arxiv.org/api/query?search_query=cat:cs.AI&sortBy=submittedDate&sortOrder=descending&max_results=30",
    type: "arxiv_api",
    category: "research",
    tier: 4,
    priority: "low",
    weight: 5,
    refreshIntervalMinutes: 720,
    description: "arXiv cs.AI — newest 30 submissions, via official Atom API.",
    tags: ["research", "arxiv"],
  },
  {
    id: "arxiv-cs-lg",
    name: "arXiv cs.LG",
    url: "https://export.arxiv.org/api/query?search_query=cat:cs.LG&sortBy=submittedDate&sortOrder=descending&max_results=30",
    type: "arxiv_api",
    category: "research",
    tier: 4,
    priority: "low",
    weight: 5,
    refreshIntervalMinutes: 720,
    description: "arXiv cs.LG — newest 30 submissions, via official Atom API.",
    tags: ["research", "arxiv"],
  },
];
